language: ruby
cache:
- bundler
script:
  - bundle exec middleman build --clean
  - bundle exec rake jasmine:ci
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master
